-- MySQL Script generated by MySQL Workbench
-- Mon Oct 28 15:47:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`version`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`version` ;

CREATE TABLE IF NOT EXISTS `mydb`.`version` (
  `id` INT NOT NULL,
  `create_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`study`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`study` ;

CREATE TABLE IF NOT EXISTS `mydb`.`study` (
  `study_id` INT NOT NULL,
  `version_id` INT NOT NULL,
  PRIMARY KEY (`study_id`, `version_id`),
  INDEX `fk_study_version1_idx` (`version_id` ASC),
  CONSTRAINT `fk_study_version1`
    FOREIGN KEY (`version_id`)
    REFERENCES `mydb`.`version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`arm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`arm` ;

CREATE TABLE IF NOT EXISTS `mydb`.`arm` (
  `arm_id` INT NOT NULL,
  `code` VARCHAR(45) NULL,
  `study_study_id` INT NULL,
  `version_id` INT NOT NULL,
  PRIMARY KEY (`arm_id`, `version_id`),
  INDEX `fk_arm_study_idx` (`study_study_id` ASC),
  INDEX `fk_arm_version1_idx` (`version_id` ASC),
  CONSTRAINT `fk_arm_study`
    FOREIGN KEY (`study_study_id`)
    REFERENCES `mydb`.`study` (`study_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arm_version1`
    FOREIGN KEY (`version_id`)
    REFERENCES `mydb`.`version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`site` ;

CREATE TABLE IF NOT EXISTS `mydb`.`site` (
  `site_id` INT NOT NULL,
  `study_study_id` INT NOT NULL,
  PRIMARY KEY (`site_id`, `study_study_id`),
  INDEX `fk_site_study1_idx` (`study_study_id` ASC),
  CONSTRAINT `fk_site_study1`
    FOREIGN KEY (`study_study_id`)
    REFERENCES `mydb`.`study` (`study_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`treatment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`treatment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`treatment` (
  `treatment_id` INT NOT NULL,
  `version_id` INT NOT NULL,
  `level_code` VARCHAR(45) NULL,
  `level_display` VARCHAR(45) NULL,
  PRIMARY KEY (`treatment_id`, `version_id`),
  INDEX `fk_treatment_version1_idx` (`version_id` ASC),
  CONSTRAINT `fk_treatment_version1`
    FOREIGN KEY (`version_id`)
    REFERENCES `mydb`.`version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`criterion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`criterion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`criterion` (
  `criterion_id` INT NOT NULL,
  `version_id` INT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `display_name` VARCHAR(45) NULL,
  PRIMARY KEY (`criterion_id`, `version_id`),
  INDEX `fk_criterion_version1_idx` (`version_id` ASC),
  CONSTRAINT `fk_criterion_version1`
    FOREIGN KEY (`version_id`)
    REFERENCES `mydb`.`version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`elegibility_criteria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`elegibility_criteria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`elegibility_criteria` (
  `elegibility_criteria_id` INT NOT NULL,
  `value` VARCHAR(45) NULL,
  `version_id` INT NOT NULL,
  `arm_arm_id` INT NOT NULL,
  `arm_version_id` INT NOT NULL,
  `criterion_criterion_id` INT NOT NULL,
  `criterion_version_id` INT NOT NULL,
  PRIMARY KEY (`elegibility_criteria_id`, `version_id`, `arm_arm_id`, `arm_version_id`, `criterion_criterion_id`, `criterion_version_id`),
  INDEX `fk_elegibility_criteria_version1_idx` (`version_id` ASC),
  INDEX `fk_elegibility_criteria_arm1_idx` (`arm_arm_id` ASC, `arm_version_id` ASC),
  INDEX `fk_elegibility_criteria_criterion1_idx` (`criterion_criterion_id` ASC, `criterion_version_id` ASC),
  CONSTRAINT `fk_elegibility_criteria_version1`
    FOREIGN KEY (`version_id`)
    REFERENCES `mydb`.`version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_elegibility_criteria_arm1`
    FOREIGN KEY (`arm_arm_id` , `arm_version_id`)
    REFERENCES `mydb`.`arm` (`arm_id` , `version_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_elegibility_criteria_criterion1`
    FOREIGN KEY (`criterion_criterion_id` , `criterion_version_id`)
    REFERENCES `mydb`.`criterion` (`criterion_id` , `version_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`value` ;

CREATE TABLE IF NOT EXISTS `mydb`.`value` (
  `value_id` INT NOT NULL,
  `value_code` VARCHAR(45) NULL,
  `value_type` VARCHAR(45) NULL,
  `display_value` VARCHAR(45) NULL,
  `upper_threshold` DECIMAL(19,4) NULL,
  `lower_threshold` DECIMAL(19,4) NULL,
  `version_id` INT NOT NULL,
  PRIMARY KEY (`value_id`, `version_id`),
  INDEX `fk_value_version1_idx` (`version_id` ASC),
  CONSTRAINT `fk_value_version1`
    FOREIGN KEY (`version_id`)
    REFERENCES `mydb`.`version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`elegibility_criteria_has_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`elegibility_criteria_has_value` ;

CREATE TABLE IF NOT EXISTS `mydb`.`elegibility_criteria_has_value` (
  `elegibility_criteria_elegibility_criteria_id` INT NOT NULL,
  `elegibility_criteria_version_id` INT NOT NULL,
  `elegibility_criteria_arm_arm_id` INT NOT NULL,
  `elegibility_criteria_arm_version_id` INT NOT NULL,
  `elegibility_criteria_criterion_criterion_id` INT NOT NULL,
  `elegibility_criteria_criterion_version_id` INT NOT NULL,
  `value_value_id` INT NOT NULL,
  `value_version_id` INT NOT NULL,
  PRIMARY KEY (`elegibility_criteria_elegibility_criteria_id`, `elegibility_criteria_version_id`, `elegibility_criteria_arm_arm_id`, `elegibility_criteria_arm_version_id`, `elegibility_criteria_criterion_criterion_id`, `elegibility_criteria_criterion_version_id`, `value_value_id`, `value_version_id`),
  INDEX `fk_elegibility_criteria_has_value_value1_idx` (`value_value_id` ASC, `value_version_id` ASC),
  INDEX `fk_elegibility_criteria_has_value_elegibility_criteria1_idx` (`elegibility_criteria_elegibility_criteria_id` ASC, `elegibility_criteria_version_id` ASC, `elegibility_criteria_arm_arm_id` ASC, `elegibility_criteria_arm_version_id` ASC, `elegibility_criteria_criterion_criterion_id` ASC, `elegibility_criteria_criterion_version_id` ASC),
  CONSTRAINT `fk_elegibility_criteria_has_value_elegibility_criteria1`
    FOREIGN KEY (`elegibility_criteria_elegibility_criteria_id` , `elegibility_criteria_version_id` , `elegibility_criteria_arm_arm_id` , `elegibility_criteria_arm_version_id` , `elegibility_criteria_criterion_criterion_id` , `elegibility_criteria_criterion_version_id`)
    REFERENCES `mydb`.`elegibility_criteria` (`elegibility_criteria_id` , `version_id` , `arm_arm_id` , `arm_version_id` , `criterion_criterion_id` , `criterion_version_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_elegibility_criteria_has_value_value1`
    FOREIGN KEY (`value_value_id` , `value_version_id`)
    REFERENCES `mydb`.`value` (`value_id` , `version_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`algorithm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`algorithm` ;

CREATE TABLE IF NOT EXISTS `mydb`.`algorithm` (
  `algorithm_id` INT NOT NULL,
  `version_id` INT NOT NULL,
  `code` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `funstion` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`algorithm_id`, `version_id`),
  INDEX `fk_algorithm_version1_idx` (`version_id` ASC),
  CONSTRAINT `fk_algorithm_version1`
    FOREIGN KEY (`version_id`)
    REFERENCES `mydb`.`version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`arm_treatment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`arm_treatment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`arm_treatment` (
  `arm_arm_id` INT NOT NULL,
  `arm_version_id` INT NOT NULL,
  `treatment_treatment_id` INT NOT NULL,
  `treatment_version_id` INT NOT NULL,
  PRIMARY KEY (`arm_arm_id`, `arm_version_id`, `treatment_treatment_id`, `treatment_version_id`),
  INDEX `fk_arm_has_treatment_treatment1_idx` (`treatment_treatment_id` ASC, `treatment_version_id` ASC),
  INDEX `fk_arm_has_treatment_arm1_idx` (`arm_arm_id` ASC, `arm_version_id` ASC),
  CONSTRAINT `fk_arm_has_treatment_arm1`
    FOREIGN KEY (`arm_arm_id` , `arm_version_id`)
    REFERENCES `mydb`.`arm` (`arm_id` , `version_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arm_has_treatment_treatment1`
    FOREIGN KEY (`treatment_treatment_id` , `treatment_version_id`)
    REFERENCES `mydb`.`treatment` (`treatment_id` , `version_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
