name: "✨ Feature Request"
description: "Suggest a new feature or enhancement"
title: "[FEATURE] <title>"
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request  
        Thank you for suggesting a new feature! Please provide the details below.

  - type: input
    id: feature-summary
    attributes:
      label: "🔹 Summary"
      description: "Briefly describe the feature."
      placeholder: "E.g., Add dark mode support"
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: "📌 Description"
      description: "Provide a detailed description of the feature."
      placeholder: "Explain why this feature is needed and how it should work."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: "🚀 Use Case"
      description: "Describe how this feature would be used."
      placeholder: "E.g., Users can enable dark mode to reduce eye strain at night."
    validations:
      required: true

  - type: dropdown
    id: feature-importance
    attributes:
      label: "⚡ Priority Level"
      description: "How important is this feature?"
      options:
        - "High (Critical for the project)"
        - "Medium (Useful but not urgent)"
        - "Low (Nice to have)"
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: "📌 Additional Information"
      description: "Any extra details or references."

  - type: checkboxes
    id: checklist
    attributes:
      label: "✔️ Checklist"
      description: "Please confirm the following:"
      options:
        - label: "I have searched for existing feature requests to avoid duplicates."
          required: true
        - label: "I have provided all necessary details."
          required: true
        - label: "I am willing to work on this feature (optional)."
