"""Modified criterion_staging model: criterion_values and echc_value_ids.

Revision ID: 078537cccdd9
Revises: 98aa0da41177
Create Date: 2025-01-29 12:32:00.786012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '078537cccdd9'
down_revision = '98aa0da41177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterion_staging', sa.Column('criterion_values', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('criterion_staging', sa.Column('echc_value_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('criterion_staging', 'el_criteria_has_criterion_id')
    op.drop_column('criterion_staging', 'values')
    op.drop_column('criterion_staging', 'echc_value_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterion_staging', sa.Column('echc_value_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('criterion_staging', sa.Column('values', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('criterion_staging', sa.Column('el_criteria_has_criterion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('criterion_staging', 'echc_value_ids')
    op.drop_column('criterion_staging', 'criterion_values')
    # ### end Alembic commands ###
