"""Added country, city, state, zip to site model.

Revision ID: 3a26a8e3543c
Revises: 14f21c3d226d
Create Date: 2023-11-27 12:42:10.934316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a26a8e3543c'
down_revision = '14f21c3d226d'
branch_labels = None
depends_on = None

def upgrade():
    op.add_column('site', sa.Column('source_id', sa.Integer(), nullable=True))
    op.add_column('site', sa.Column('country', sa.String(), nullable=True))
    op.add_column('site', sa.Column('city', sa.String(), nullable=True))
    op.add_column('site', sa.Column('state', sa.String(), nullable=True))
    op.add_column('site', sa.Column('zip', sa.String(), nullable=True))
    op.create_unique_constraint('site_uix', 'site', ['name', 'zip'])
    op.create_foreign_key('fk_site_source_id', 'site', 'source', ['source_id'], ['id'])
    op.drop_column('site', 'active')
    op.drop_column('site', 'code')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_site_source_id', 'site', type_='foreignkey')
    op.drop_constraint('site_uix', 'site', type_='unique')
    op.drop_column('site', 'zip')
    op.drop_column('site', 'state')
    op.drop_column('site', 'city')
    op.drop_column('site', 'country')
    op.drop_column('site', 'source_id')
    # ### end Alembic commands ###
