"""Added not null constraint to study_version.status and eligibility_criteria.status.

Revision ID: 4ff089373353
Revises: 241619ddac70
Create Date: 2024-11-07 12:46:42.837498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ff089373353'
down_revision = '241619ddac70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE study_version SET status = 'ACTIVE', eligibility_criteria_id = 1, study_algorithm_engine_id = 1 where id = 1")
    op.execute("UPDATE study_version SET status = 'ACTIVE', eligibility_criteria_id = 2, study_algorithm_engine_id = 2 where id = 2")
    op.execute("UPDATE study_version SET status = 'INACTIVE', eligibility_criteria_id = 3, study_algorithm_engine_id = 3 where id = 3")
    op.execute("UPDATE study_version SET status = 'INACTIVE' where id = 4")
    op.execute("UPDATE study_version SET status = 'INACTIVE', eligibility_criteria_id = 5, study_algorithm_engine_id = 5 where id = 5")
    op.execute("UPDATE study_version SET status = 'ACTIVE', eligibility_criteria_id = 6, study_algorithm_engine_id = 6 where id = 6")
    op.execute("UPDATE study_version SET status = 'INACTIVE', eligibility_criteria_id = 7, study_algorithm_engine_id = 7 where id = 7")
    op.execute("UPDATE study_version SET status = 'ACTIVE', eligibility_criteria_id = 8, study_algorithm_engine_id = 8 where id = 8")
    op.execute("UPDATE study_version SET status = 'ACTIVE', eligibility_criteria_id = 9, study_algorithm_engine_id = 9 where id = 9")
    op.execute("UPDATE study_version SET status = 'ACTIVE', eligibility_criteria_id = 10, study_algorithm_engine_id = 10 where id = 10")
    op.execute("UPDATE study_version SET status = 'ACTIVE', eligibility_criteria_id = 11, study_algorithm_engine_id = 11 where id = 11")
    op.execute("UPDATE study_version SET status = 'INACTIVE', eligibility_criteria_id = 12, study_algorithm_engine_id = 12 where id = 12")
    op.execute("UPDATE study_version SET status = 'INACTIVE', eligibility_criteria_id = 13, study_algorithm_engine_id = 13 where id = 13")
    op.execute("UPDATE study_version SET status = 'ACTIVE', eligibility_criteria_id = 14, study_algorithm_engine_id = 14 where id = 14")
    op.execute("UPDATE study_version SET status = 'INACTIVE', eligibility_criteria_id = 15, study_algorithm_engine_id = 15 where id = 15")
    op.execute("UPDATE study_version SET status = 'ACTIVE', eligibility_criteria_id = 16, study_algorithm_engine_id = 16 where id = 16")
    op.execute("UPDATE study_version SET status = 'ACTIVE', eligibility_criteria_id = 17, study_algorithm_engine_id = 17 where id = 17")
    op.execute("UPDATE criterion set active = true")
    op.execute("UPDATE eligibility_criteria set status = 'ACTIVE'")


    op.alter_column('criterion_staging', 'criterion_adjudication_status',
               existing_type=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='adjudication_status'),
               type_=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='adjudication_status'),
               existing_nullable=False)
    op.alter_column('criterion_staging', 'echc_adjudication_status',
               existing_type=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='echc_adjudication_status'),
               type_=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='echc_adjudication_status'),
               existing_nullable=False)
    op.alter_column('eligibility_criteria', 'status',
               existing_type=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='eligibility_criteria_status'),
               nullable=False)
    op.alter_column('study_version', 'status',
               existing_type=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='study_version_status'),
               type_=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='study_version_status'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_version', 'status',
               existing_type=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='study_version_status'),
               type_=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='study_version_status'),
               nullable=True)
    op.alter_column('eligibility_criteria', 'status',
               existing_type=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='eligibility_criteria_status'),
               nullable=True)
    op.alter_column('criterion_staging', 'echc_adjudication_status',
               existing_type=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='echc_adjudication_status'),
               type_=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='echc_adjudication_status'),
               existing_nullable=False)
    op.alter_column('criterion_staging', 'criterion_adjudication_status',
               existing_type=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='adjudication_status'),
               type_=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='adjudication_status'),
               existing_nullable=False)
    # ### end Alembic commands ###
