"""Added not null constraint to study_version.status and eligibility_criteria.status.

Revision ID: 4ff089373353
Revises: 241619ddac70
Create Date: 2024-11-07 12:46:42.837498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ff089373353'
down_revision = '241619ddac70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('criterion_staging', 'criterion_adjudication_status',
               existing_type=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='adjudication_status'),
               type_=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='adjudication_status'),
               existing_nullable=False)
    op.alter_column('criterion_staging', 'echc_adjudication_status',
               existing_type=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='echc_adjudication_status'),
               type_=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='echc_adjudication_status'),
               existing_nullable=False)
    op.alter_column('eligibility_criteria', 'status',
               existing_type=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='eligibility_criteria_status'),
               nullable=False)
    op.alter_column('study_version', 'status',
               existing_type=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='study_version_status'),
               type_=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='study_version_status'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_version', 'status',
               existing_type=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='study_version_status'),
               type_=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='study_version_status'),
               nullable=True)
    op.alter_column('eligibility_criteria', 'status',
               existing_type=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='eligibility_criteria_status'),
               nullable=True)
    op.alter_column('criterion_staging', 'echc_adjudication_status',
               existing_type=postgresql.ENUM('NEW', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='echc_adjudication_status'),
               type_=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='echc_adjudication_status'),
               existing_nullable=False)
    op.alter_column('criterion_staging', 'criterion_adjudication_status',
               existing_type=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='adjudication_status'),
               type_=postgresql.ENUM('NEW', 'EXISTING', 'ACTIVE', 'IN_PROCESS', 'INACTIVE', name='adjudication_status'),
               existing_nullable=False)
    # ### end Alembic commands ###
