"""Added source table and relationships, mods to site - removed active added location info.

Revision ID: 5ed675c4e2da
Revises: 0d8f98ceec8d
Create Date: 2024-01-04 13:49:29.675653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed675c4e2da'
down_revision = '0d8f98ceec8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', name='source_uix')
    )
    op.add_column('study', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_study_source_id', 'study', 'source', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_study_source_id', 'study', type_='foreignkey')
    op.drop_column('study', 'source_id')
    op.drop_table('source')
    # ### end Alembic commands ###
