"""Rename study_version to study_version_num in study_version table.

Revision ID: 5f582ee52375
Revises: 5ed675c4e2da
Create Date: 2024-01-05 14:27:49.689676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f582ee52375'
down_revision = '5ed675c4e2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_version', sa.Column('study_version_num', sa.Integer(), nullable=True))
    op.drop_column('study_version', 'study_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_version', sa.Column('study_version', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('study_version', 'study_version_num')
    # ### end Alembic commands ###
