"""Added eligibility_criteria_info table fix.

Revision ID: 6ace87aa7e5d
Revises: 5f38941a18aa
Create Date: 2023-03-11 22:43:58.295218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ace87aa7e5d'
down_revision = '5f38941a18aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eligibility_criteria_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('study_version_id', sa.Integer(), nullable=True),
    sa.Column('study_algorithm_engine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['study_algorithm_engine_id'], ['study_algorithm_engine.id'], ),
    sa.ForeignKeyConstraint(['study_version_id'], ['study_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eligibility_criteria_info')
    # ### end Alembic commands ###
