"""Modified value model, removed code.

Revision ID: 7b2f5dbef9e5
Revises: 7c31cc75cb6e
Create Date: 2024-02-13 11:27:43.847536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2f5dbef9e5'
down_revision = '7c31cc75cb6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('value_code_uix', 'value', type_='unique')
    op.drop_constraint('value_code_unit_uix', 'value', type_='unique')
    op.create_unique_constraint('value_num_unit_op_uix', 'value', ['is_numeric', 'unit_id', 'value_string', 'operator'])
    op.drop_column('value', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('value', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('value_num_unit_op_uix', 'value', type_='unique')
    op.create_unique_constraint('value_code_unit_uix', 'value', ['is_numeric', 'unit_id', 'value_string', 'operator'])
    op.create_unique_constraint('value_code_uix', 'value', ['code'])
    # ### end Alembic commands ###
