"""Modified value model, changed type to is_numeric.

Revision ID: 7c31cc75cb6e
Revises: e663a92dea18
Create Date: 2024-02-08 14:10:47.690100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c31cc75cb6e'
down_revision = 'e663a92dea18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('value', sa.Column('is_numeric', sa.Boolean(), nullable=True))
    op.drop_constraint('value_code_unit_uix', 'value', type_='unique')
    op.create_unique_constraint('value_code_unit_uix', 'value', ['is_numeric', 'unit_id', 'value_string', 'operator'])
    op.drop_column('value', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('value', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('value_code_unit_uix', 'value', type_='unique')
    op.create_unique_constraint('value_code_unit_uix', 'value', ['type', 'unit_id', 'value_string', 'operator'])
    op.drop_column('value', 'is_numeric')
    # ### end Alembic commands ###
