"""Added el_criteria_has_criterion_id to criterion_staging.

Revision ID: 81723c9ecb28
Revises: d65c6a300bce
Create Date: 2024-08-20 14:53:56.542236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81723c9ecb28'
down_revision = 'd65c6a300bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterion_staging', sa.Column('el_criteria_has_criterion_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criterion_staging', 'el_criteria_has_criterion_id')
    # ### end Alembic commands ###
