"""full schema first migration

Revision ID: a10750c00d87
Revises: 347625f5a777
Create Date: 2022-01-12 15:23:13.410282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10750c00d87'
down_revision = '347625f5a777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
