"""Added echc_value_id to criterion_staging.

Revision ID: d65c6a300bce
Revises: 7b8a2262145a
Create Date: 2024-08-19 12:15:23.261274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd65c6a300bce'
down_revision = '7b8a2262145a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterion_staging', sa.Column('echc_value_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criterion_staging', 'echc_value_id')
    # ### end Alembic commands ###
