"""Added unique constraint on source.priority.

Revision ID: e2dafa86eee0
Revises: 5f582ee52375
Create Date: 2024-01-16 16:36:23.034615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2dafa86eee0'
down_revision = '5f582ee52375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('priority_uix', 'source', ['priority'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('priority_uix', 'source', type_='unique')
    # ### end Alembic commands ###
