"""Added unit table and relationships.

Revision ID: e663a92dea18
Revises: 96781d481b2e
Create Date: 2024-02-07 13:34:45.208868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e663a92dea18'
down_revision = '96781d481b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='unit_name_uix')
    )
    op.add_column('value', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.drop_constraint('value_code_unit_uix', 'value', type_='unique')
    op.create_unique_constraint('value_code_unit_uix', 'value', ['type', 'unit_id', 'value_string', 'operator'])
    op.create_foreign_key('fk_value_unit_id', 'value', 'unit', ['unit_id'], ['id'])
    op.drop_column('value', 'unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('value', sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_value_unit_id', 'value', type_='foreignkey')
    op.drop_constraint('value_code_unit_uix', 'value', type_='unique')
    op.create_unique_constraint('value_code_unit_uix', 'value', ['type', 'unit', 'value_string', 'operator'])
    op.drop_column('value', 'unit_id')
    op.drop_table('unit')
    # ### end Alembic commands ###
