-- MySQL Script generated by MySQL Workbench
-- Mon Jun 15 14:09:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pedal_dev_v_0
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pedal_dev_v_0` ;

-- -----------------------------------------------------
-- Schema pedal_dev_v_0
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pedal_dev_v_0` DEFAULT CHARACTER SET utf8 ;
USE `pedal_dev_v_0` ;

-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`study`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`study` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`study` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  `create_date` DATETIME NULL,
  `active` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`study_version`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`study_version` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`study_version` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `study_id` INT NOT NULL,
  `create_date` DATETIME NULL,
  `active` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_study_version_study1_idx` (`study_id` ASC),
  CONSTRAINT `fk_study_version_study1`
    FOREIGN KEY (`study_id`)
    REFERENCES `pedal_dev_v_0`.`study` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`site` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`site` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `create_date` DATETIME NULL,
  `active` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`criterion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`criterion` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`criterion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(512) NULL,
  `display_name` VARCHAR(128) NULL,
  `description` VARCHAR(512) NULL,
  `create_date` DATETIME NULL,
  `active` TINYINT NULL,
  `ontology_code_id` INT NULL,
  `input_type_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_criterion_ontology_code1_idx` (`ontology_code_id` ASC),
  INDEX `fk_criterion_input_type1_idx` (`input_type_id` ASC),
  CONSTRAINT `fk_criterion_ontology_code1`
    FOREIGN KEY (`ontology_code_id`)
    REFERENCES `pedal_dev_v_0`.`ontology_code` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_criterion_input_type1`
    FOREIGN KEY (`input_type_id`)
    REFERENCES `pedal_dev_v_0`.`input_type` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`ontology_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`ontology_code` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`ontology_code` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ontology_url` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  `value` VARCHAR(45) NULL,
  `version` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`eligibility_criteria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`eligibility_criteria` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`eligibility_criteria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_date` DATETIME NULL,
  `active` TINYINT NULL,
  `study_version_id` INT NOT NULL,  
  PRIMARY KEY (`id`),
  INDEX `fk_eligibility_criteria_study_version1_idx` (`study_version_id` ASC),  
    CONSTRAINT `fk_eligibility_criteria_study_version1`
    FOREIGN KEY (`study_version_id`)
    REFERENCES `pedal_dev_v_0`.`study_version` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`el_criteria_has_criterion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`el_criteria_has_criterion` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`el_criteria_has_criterion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `criterion_id` INT NOT NULL,
  `eligibility_criteria_id` INT NOT NULL,
  `create_date` DATETIME NULL,
  `active` TINYINT NULL,
  `value_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_el_criteria_has_criterion_criterion1_idx` (`criterion_id` ASC),
  INDEX `fk_el_criteria_has_criterion_eligibility_criteria1_idx` (`eligibility_criteria_id` ASC),
  INDEX `fk_el_criteria_has_criterion_value1_idx` (`value_id` ASC),
  CONSTRAINT `fk_el_criteria_has_criterion_criterion1`
    FOREIGN KEY (`criterion_id`)
    REFERENCES `pedal_dev_v_0`.`criterion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_el_criteria_has_criterion_eligibility_criteria1`
    FOREIGN KEY (`eligibility_criteria_id`)
    REFERENCES `pedal_dev_v_0`.`eligibility_criteria` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_el_criteria_has_criterion_value1`
    FOREIGN KEY (`value_id`)
    REFERENCES `pedal_dev_v_0`.`value` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`value` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`value` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(512) NULL,
  `description` VARCHAR(512) NULL,
  `type` VARCHAR(45) NULL,
  `value_string` VARCHAR(45) NULL,
  `unit` VARCHAR(45) NULL,
  `operator` VARCHAR(45) NULL,
  `create_date` DATETIME NULL,
  `active` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`eligibility_criteria_has_note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`eligibility_criteria_has_note` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`eligibility_criteria_has_note` (
  `eligibility_criteria_id` INT NOT NULL,
  `note_id` INT NOT NULL,
  PRIMARY KEY (`eligibility_criteria_id`, `note_id`),
  INDEX `fk_eligibility_criteria_has_note_eligibility_criteria1_idx` (`eligibility_criteria_id` ASC),
  INDEX `fk_eligibility_criteria_has_note_note1_idx` (`note_id` ASC),
  CONSTRAINT `fk_eligibility_criteria_has_note_eligibility_criteria1`
    FOREIGN KEY (`eligibility_criteria_id`)
    REFERENCES `pedal_dev_v_0`.`eligibility_criteria` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_eligibility_criteria_has_note_note1`
    FOREIGN KEY (`note_id`)
    REFERENCES `pedal_dev_v_0`.`note` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`note` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`note` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`tag` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`input_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`input_type` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`input_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_type` VARCHAR(45) NULL,
  `render_type` VARCHAR(45) NULL,
  `create_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`algorithm_engine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`algorithm_engine` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`algorithm_engine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `el_criteria_has_criterion_id` INT NOT NULL,
  `parent_id` INT NOT NULL,
  `parent_path` VARCHAR(512) NOT NULL,
  `operator` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_algorithm_engine_el_criteria_has_criterion1_idx` (`el_criteria_has_criterion_id` ASC),
  CONSTRAINT `fk_algorithm_engine_el_criteria_has_criterion1`
    FOREIGN KEY (`el_criteria_has_criterion_id`)
    REFERENCES `pedal_dev_v_0`.`el_criteria_has_criterion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`study_algorithm_engine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`study_algorithm_engine` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`study_algorithm_engine` (
  `study_version_id` INT NOT NULL,
  `algorithm_engine_id` INT NOT NULL,
  `start_date` DATETIME NULL,
  `active` TINYINT NULL,
  PRIMARY KEY (`study_version_id`, `algorithm_engine_id`),
  INDEX `fk_study_algorithm_engine_study_version1_idx` (`study_version_id` ASC),
  INDEX `fk_study_algorithm_engine_algorithm_engine1_idx` (`algorithm_engine_id` ASC),
  CONSTRAINT `fk_study_algorithm_engine_study_version1`
    FOREIGN KEY (`study_version_id`)
    REFERENCES `pedal_dev_v_0`.`study_version` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_study_algorithm_engine_algorithm_engine1`
    FOREIGN KEY (`algorithm_engine_id`)
    REFERENCES `pedal_dev_v_0`.`algorithm_engine` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`site_has_study`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`site_has_study` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`site_has_study` (
  `site_id` INT NOT NULL,
  `study_id` INT NOT NULL,
  `create_date` DATETIME NULL,
  `active` TINYINT NULL,
  PRIMARY KEY (`site_id`, `study_id`),
  INDEX `fk_site_has_study_study1_idx` (`study_id` ASC),
  INDEX `fk_site_has_study_site1_idx` (`site_id` ASC),
  CONSTRAINT `fk_site_has_study_site1`
    FOREIGN KEY (`site_id`)
    REFERENCES `pedal_dev_v_0`.`site` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_site_has_study_study1`
    FOREIGN KEY (`study_id`)
    REFERENCES `pedal_dev_v_0`.`study` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`criterion_has_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`criterion_has_tag` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`criterion_has_tag` (
  `criterion_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`criterion_id`, `tag_id`),
  INDEX `fk_criterion_has_tag_criterion1_idx` (`criterion_id` ASC),
  INDEX `fk_criterion_has_tag_tag1_idx` (`tag_id` ASC),
  CONSTRAINT `fk_criterion_has_tag_criterion1`
    FOREIGN KEY (`criterion_id`)
    REFERENCES `pedal_dev_v_0`.`criterion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_criterion_has_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `pedal_dev_v_0`.`tag` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`logins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`logins` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`logins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sub_id` VARCHAR(45) NOT NULL,
  `refresh_token` MEDIUMTEXT NOT NULL,
  `iat` DATETIME NULL,
  `exp` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`display_rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`display_rules` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`display_rules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `criterion_id` INT NOT NULL,
  `priority` INT NOT NULL,
  `active` TINYINT NULL,
  `version` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_display_rules_criterion1_idx` (`criterion_id` ASC),
  CONSTRAINT `fk_display_rules_criterion1`
    FOREIGN KEY (`criterion_id`)
    REFERENCES `pedal_dev_v_0`.`criterion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`triggered_by`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`triggered_by` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`triggered_by` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `display_rules_id` INT NOT NULL,
  `criterion_id` INT NOT NULL,
  `value_id` INT NOT NULL,
  `path` VARCHAR(255) NULL,
  `active` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_triggered_by_display_rules1_idx` (`display_rules_id` ASC),
  INDEX `fk_triggered_by_criterion1_idx` (`criterion_id` ASC),
  INDEX `fk_triggered_by_value1_idx` (`value_id` ASC),
  CONSTRAINT `fk_triggered_by_display_rules1`
    FOREIGN KEY (`display_rules_id`)
    REFERENCES `pedal_dev_v_0`.`display_rules` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_triggered_by_criterion1`
    FOREIGN KEY (`criterion_id`)
    REFERENCES `pedal_dev_v_0`.`criterion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_triggered_by_value1`
    FOREIGN KEY (`value_id`)
    REFERENCES `pedal_dev_v_0`.`value` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pedal_dev_v_0`.`criterion_has_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedal_dev_v_0`.`criterion_has_value` ;

CREATE TABLE IF NOT EXISTS `pedal_dev_v_0`.`criterion_has_value` (
  `criterion_id` INT NOT NULL,
  `value_id` INT NOT NULL,
  `create_date` DATETIME NULL,
  PRIMARY KEY (`criterion_id`, `value_id`),
  INDEX `fk_criterion_has_value_criterion1_idx` (`criterion_id` ASC),
  INDEX `fk_criterion_has_value_value1_idx` (`value_id` ASC),
  CONSTRAINT `fk_criterion_has_value_criterion1`
    FOREIGN KEY (`criterion_id`)
    REFERENCES `pedal_dev_v_0`.`criterion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_criterion_has_value_value1`
    FOREIGN KEY (`value_id`)
    REFERENCES `pedal_dev_v_0`.`value` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
